typography_spectrum: 0.76206
color:
  brandColors:
    - '#ffffff'
    - '#005596'
    - '#2b72a7'
    - '#a7c4db'
    - '#6699bf'
  brandStrength: 0.6872846600599587
  lightness: 0.6890843452420086
  saturation: 0.5979883018881083
  rhythmicContrast: 0.020094469422474504
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.27714
analytics:
  google: null
  facebook: null
  twitter: null
name: Peak Writing Services
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: get it writ the first time
purpose: []
